GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTc2MzU0MDk3Mn0.4VK-q3dwzTLpL3z_DU_A4yifWd_I7wj7cuDzVkuj3Nw

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Kyle"
}